### ISSUE TITLE
Wrong password in token

### ISSUE THREAD

**Issue by alexghergh** [CNITV/SQLiggyBank#24]
The password in the JWT token is not stored correctly. It differs from the password stored in the database, and as such the user cannot be verified correctly. 

This leads to different problems where the user cannot delete their account or modify the data.

**Comment by StormFireFox1** [comment]
This isn't a problem with the implementation of JWT's, but a problem with the original endpoints, since they check authentication incorrectly. I will fix this soon.

**Comment by StormFireFox1** [comment]
Fixed in [this commit](https://github.com/CNITV/SQLiggyBank/commit/ef729e11ebcef8a019a6269255f999ecd7863066). I will check if any other resource executes a similar improper handling of the password and fix in time.
