### ISSUE TITLE
[Feature] Remove UUID's from being publicly seen

### ISSUE THREAD

**Issue by alexghergh** [CNITV/SQLiggyBank#25]
The UUID's (of users, banks, groups, etc.) bring no information to the user. They are used only by the API itself, and so consider removing them completely from the responses (similar to the passwords).

**Comment by StormFireFox1** [comment]
Fixed in [this commit](https://github.com/CNITV/SQLiggyBank/commit/cf70649f1991e44505ce7e35adb0433b86aec0fc).

**Comment by StormFireFox1** [comment]
Alright, that seems reasonable. Hopefully nothing breaks on the client side.

-- 
Matei-Alexandru Gardus (Storm_FireFox1)
https://stormhub.io

**Comment by alexghergh** [comment]
Rechecking this issue looks like not all the fields were correctly annotated by https://github.com/CNITV/SQLiggyBank/commit/cf70649f1991e44505ce7e35adb0433b86aec0fc

I.E. the User class has the UUID left alone, which should be annotated as well.

**Comment by alexghergh** [comment]
Also, having the feature approved, the endpoint **{{host}}/api/users/{{username}} (authenticated)** seems redundant (became exactly the same to **{{host}}/api/users/{{username}} (not authenticated)**), but the dev might leave it for historic or compatibility reasons.

**Comment by StormFireFox1** [comment]
> Rechecking this issue looks like not all the fields were correctly annotated by [cf70649](https://github.com/CNITV/SQLiggyBank/commit/cf70649f1991e44505ce7e35adb0433b86aec0fc)
> 
> I.E. the User class has the UUID left alone, which should be annotated as well.

Fixed in [this commit](https://github.com/CNITV/SQLiggyBank/commit/8ad8441e29eeae26175b152083eeb6765d461117).

**Comment by StormFireFox1** [comment]
On 19/06/06 04:15AM, Alexandru Gherghescu wrote:
> Also, having the feature approved, the endpoint **{{host}}/api/users/{{username}} (authenticated)** seems redundant (became exactly the same to **{{host}}/api/users/{{username}} (not authenticated)**), but the dev might leave it for historic or compatibility reasons.

I mostly kept it over time to keep fluidity amongst all endpoints (all of them
check for authentication, perhaps one day I will refactor the checking for
authentication into a different method), but I am considering removing it soon.

-- 
Matei-Alexandru Gardus (Storm_FireFox1)
https://stormhub.io
