### ISSUE TITLE
[Feature] Delete (possible) redundant API endpoint

### ISSUE THREAD

**Issue by alexghergh** [CNITV/SQLiggyBank#27]
The endpoint **{{host}}/api/lists/{{testGroupName}}** doesn't seem to be used for anything.

There are better versions in the form of: 

**{{host}}/api/lists/groups/{{username}}** 
**{{host}}/api/lists/members/{{testGroupName}}**

**Comment by StormFireFox1** [comment]
Fixed in [this commit](https://github.com/CNITV/SQLiggyBank/commit/144218b5fea397fb01b8a83fff5c01e3184176dc).
