### ISSUE TITLE
[Bug] Trying to delete a user that is owner of a group

### ISSUE THREAD

**Issue by alexghergh** [CNITV/SQLiggyBank#29]
The server doesn't correctly handle cases where a user that owns one or multiple groups tries to delete their account.

It should first try to delete the goals/banks of a group, then the item in the groups_list corresponding to the user-group information, then the group and then the user itself (hope I didn't miss anything).

**Comment by StormFireFox1** [comment]
On 19/06/06 04:31AM, Alexandru Gherghescu wrote:
> The server doesn't correctly handle cases where a user that owns one or multiple groups tries to delete their account.
> 
> It should first try to delete the goals/banks of a group, then the item in the groups_list corresponding to the user-group information, then the group and then the user itself (hope I didn't miss anything).

Well, there is a bit of debate to be had here as to what happens to the group.
Who gets owner permissions if the owner gets deleted? Should it be picked at
random? Do we just implement a new "owner" system? I'm thinking "pick at random"
is the easiest to implement, but obviously that's a bad idea. What do you think?

-- 
Matei-Alexandru Gardus (Storm_FireFox1)
https://stormhub.io

**Comment by alexghergh** [comment]
In my opinion, we could either:
**a.** Create a new endpoint allowing the owner of a group to be able to give ownership to another person in the group (if it exists), or
**b.** Delete the group entirely, with all the people in it, or
**c.** (Not really an option I think) Give random ownership of the group.

How do these proposals look?

**Comment by StormFireFox1** [comment]
On 19/06/08 10:44AM, Alexandru Gherghescu wrote:
> **a.** Create a new endpoint allowing the owner of a group to be able to give ownership to another person in the group (if it exists), or

Well, this seems like the obvious choice, honestly. Gonna take a bit more time
to implement, but it's doable, I suppose. I'm keeping this issue open until we
both write the code for this. I'm gonna make an issue for this as well.

-- 
Matei-Alexandru Gardus (Storm_FireFox1)
https://stormhub.io

**Comment by alexghergh** [comment]
Since there is another issue for this problem, I'm going to close this.

(Related issue #39)
