### ISSUE TITLE
[Bug] Group invites are no longer available

### ISSUE THREAD

**Issue by alexghergh** [CNITV/SQLiggyBank#30]
Due to a recent commit (exactly https://github.com/CNITV/SQLiggyBank/commit/cf70649f1991e44505ce7e35adb0433b86aec0fc), the UUID's of the invites are no longer present in the response body of the endpoint for creating new invites for a group, and as such users cannot join groups via invites.

**Comment by StormFireFox1** [comment]
Yeah, that was stupid on my part. I'll remove the annotation now.

-- 
Matei-Alexandru Gardus (Storm_FireFox1)
https://stormhub.io

**Comment by StormFireFox1** [comment]
Fixed in [this commit](https://github.com/CNITV/SQLiggyBank/commit/16cf1b120f6526e1f5863eb38f56b5449af7345d).
