### ISSUE TITLE
[Bug] Wrong query name for goal information

### ISSUE THREAD

**Issue by alexghergh** [CNITV/SQLiggyBank#33]
Badly named/no query for retrieving information for a goal.

According to [this](https://github.com/CNITV/SQLiggyBank/blob/develop/server/src/main/java/ro/lbi/sqliggybank/server/Database/GoalDAO.java#L56), there should be a query to retrieve a goal information, but there are no such queries in [the Goal resource](https://github.com/CNITV/SQLiggyBank/blob/develop/server/src/main/java/ro/lbi/sqliggybank/server/Resources/GoalResource.java).

**Comment by StormFireFox1** [comment]
Fixed in [this commit](https://github.com/CNITV/SQLiggyBank/commit/16cd77078e5dd45ef72618bf8c853c2530bc6f2b).
