### ISSUE TITLE
[Bug] Wrong name for column

### ISSUE THREAD

**Issue by alexghergh** [CNITV/SQLiggyBank#34]
The annotation name should be changed from "piggy_bank_uuid" to simply "bank_uuid" [here](https://github.com/CNITV/SQLiggyBank/blob/develop/server/src/main/java/ro/lbi/sqliggybank/server/Core/Goal.java#L46).

**Comment by StormFireFox1** [comment]
Fixed in [this commit](https://github.com/CNITV/SQLiggyBank/commit/b4cf14db548641ed47ab600d375a4908645824ef).
