### ISSUE TITLE
[Bug] Server error when trying to create a group that already exists

### ISSUE THREAD

**Issue by alexghergh** [CNITV/SQLiggyBank#37]
When you try to create a group with a name that **already exists**, the server returns a 500 error, instead of a 4xx error code.

Endpoint: **{{host}}/api/groups/new**

**Comment by StormFireFox1** [comment]
Fixed in [this commit](https://github.com/CNITV/SQLiggyBank/commit/c28e69e3dbb1ebf5219d3a066954c59355153879).
