### ISSUE TITLE
[Bug] Server error when trying to create a bank with a name that already exists

### ISSUE THREAD

**Issue by alexghergh** [CNITV/SQLiggyBank#38]
The server returns a 500 error message instead of a 4xx status code when you try to create a new bank with a name that already exists.

Endpoint **{{host}}/api/banks/{{testGroupName}}/new**

Similar to #37

**Comment by StormFireFox1** [comment]
Fixed in [this commit](https://github.com/CNITV/SQLiggyBank/commit/c28e69e3dbb1ebf5219d3a066954c59355153879).

**Comment by alexghergh** [comment]
The issue doesn't seem to be fixed, there still is a 500 server error on **banks**.

What you seem to have fixed is both **goals** and **groups**.

**Comment by alexghergh** [comment]
Please check [lines 196-197 from banks resource](https://github.com/CNITV/SQLiggyBank/blob/bugfix/bug-sprint-1/server/src/main/java/ro/lbi/sqliggybank/server/Resources/BanksResource.java#L196). It should be a BAD REQUEST on line 196.

**Comment by alexghergh** [comment]
This possibly does exist in groups and goals as well.

**Comment by StormFireFox1** [comment]
> Please check lines 196-197 from banks resource. It should be a BAD REQUEST on line 196.

Nice catch, I just fixed it in commit 3a6f4ec.

-- 
Matei-Alexandru Gardus (Storm_FireFox1)
https://stormhub.io

**Comment by StormFireFox1** [comment]
On 19/06/15 11:35AM, Alexandru Gherghescu wrote:
> This possibly does exist in groups and goals as well.

Just checked, no similar errors exist in the other Resources you mentioned.
Looks good on my end.

-- 
Matei-Alexandru Gardus (Storm_FireFox1)
https://stormhub.io
